language: english
os: ubuntu
services:
  - docker
branches:
  only:
    - main
before_install:
  - pwd
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - export DENO_INSTALL="$HOME/.deno"
  - export PATH="$DENO_INSTALL/bin:$PATH"
  - deno run https://deno.land/std/examples/welcome.ts
script:
  - make test
  - make compile
deploy:
  skip_cleanup: true
